# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 09:52
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(default=datetime.datetime.utcnow, editable=False)),
                ('full_image', models.ImageField(help_text='Choose image to upload.', upload_to=main.models.generate_image_name, validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])])),
                ('title', models.CharField(blank=True, help_text='(Optional) Image title to show.', max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.utcnow, editable=False)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.utcnow, editable=False)),
                ('title', models.CharField(max_length=80)),
                ('price', models.FloatField(help_text='Product price.', validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.TextField(help_text='Description, formatted with markdown.')),
                ('image', models.OneToOneField(help_text='Choose one of uploaded images', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.Image')),
            ],
        ),
    ]
