# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171024_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='primary_image',
            field=models.BooleanField(default=False),
        ),
    ]
